

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;




/**
 *
 * @author julio
 */
public class JFrameTablero extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    int lb2x=0;
    int lb2y=0;
    int lb3x=0;
    int lb3y=0;
    int lb4x=0;
    int lb4y=0;
    int lb5x=0;
    int lb5y=0;
    int lb6x=0;
    int lb6y=0;
    int lb7x=0;
    int lb7y=0;
    int lb8x=0;
    int lb8y=0;
    int lb9x=0;
    int lb9y=0;
    //****
    int lb11x=0;
    int lb11y=0;
    int lb12x=0;
    int lb12y=0;
    int lb13x=0;
    int lb13y=0;
    int lb14x=0;
    int lb14y=0;
    int lb15x=0;
    int lb15y=0;
    int lb16x=0;
    int lb16y=0;
    int lb17x=0;
    int lb17y=0;
    int lb18x=0;
    int lb18y=0;
    /**
     * Creates new form JFrameTablero
     */
    
    public JFrameTablero() {
        initComponents();
        //setLocationRelativeTo(null);
        t = new Timer(1000, acciones);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private Timer t;
    private int h, m, s, cs;
    private ActionListener acciones = new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent ae) {
            ++cs; 
            if(cs==100){
                cs = 0;
                ++s;
            }
            if(s==60) 
            {
                s = 0;
                ++m;
            }
            if(m==60)
            {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
        
    };
    private void actualizarLabel() {
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
        etiquetaTiempo.setText(tiempo);
    }
    public String GuardarArchivo(File archivo,String documento){
        String mensaje=null;
        try {
             salida=new FileOutputStream(archivo);
             byte[] bytxt=documento.getBytes();
             salida.write(bytxt);
             mensaje="Archivio Guardado";
        } catch (Exception e) { }
        return mensaje;
    
    }
    
    public String AbrirArchivo(File archivo) {
        String documento="";
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci=entrada.read())!=-1){
                char caracter=(char)ascci;
                documento+=caracter;
            }
            
        } catch (Exception e) {
        
        }
        return documento;
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbTablero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        etiquetaTiempo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(java.awt.Color.gray);
        setLocation(new java.awt.Point(0, 0));

        jLbTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablero.jpg"))); // NOI18N
        jLbTablero.setName(""); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BtmNegro.jpg"))); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel14MouseDragged(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel16MouseDragged(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel17MouseDragged(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BotonBlanco.jpg"))); // NOI18N
        jLabel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel18MouseDragged(evt);
            }
        });

        jButton1.setText("Inicio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        etiquetaTiempo.setEditable(false);
        etiquetaTiempo.setBackground(new java.awt.Color(204, 204, 204));
        etiquetaTiempo.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 0, 51));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etiquetaTiempo.setText("00:00:00");
        etiquetaTiempo.setCaretColor(new java.awt.Color(255, 0, 51));

        txtContenido.setEditable(false);
        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        jMenu2.setText("Juego");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem4.setText("Guardar partida");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbTablero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel16)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel17)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addGap(93, 93, 93))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLbTablero)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        jLabel2.setLocation(jLabel2.getLocation().x+evt.getX()-jLabel2.getWidth()/2, jLabel2.getLocation().y+evt.getY()-jLabel2.getHeight());
        lb2x=jLabel2.getLocation().x+evt.getX()-jLabel2.getWidth()/2;
        lb2y=jLabel2.getLocation().y+evt.getY()-jLabel2.getHeight();
         //jLabel5.setLocation(280,295);
        //jLabel6.setLocation(250,145);//2
        
        //if ((((jLabel2.getLocation().x>=296) && (jLabel2.getLocation().x<=334)) && (jLabel2.getLocation().y>=109)) && (jLabel2.getLocation().y<=134)) {System.out.println("Error");} else 
        //System.out.println("X: "+jLabel2.getLocation().x+" , "+evt.getX()+"Y "+jLabel2.getLocation().y+" , "+evt.getY());
     
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
        jLabel3.setLocation(jLabel3.getLocation().x+evt.getX()-jLabel3.getWidth()/2, jLabel3.getLocation().y+evt.getY()-jLabel3.getHeight());
        lb3x=jLabel3.getLocation().x+evt.getX()-jLabel3.getWidth()/2;
        lb3y=jLabel3.getLocation().y+evt.getY()-jLabel3.getHeight();
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        jLabel4.setLocation(jLabel4.getLocation().x+evt.getX()-jLabel4.getWidth()/2, jLabel4.getLocation().y+evt.getY()-jLabel4.getHeight());
        lb4x=jLabel4.getLocation().x+evt.getX()-jLabel4.getWidth()/2;
        lb4y=jLabel4.getLocation().y+evt.getY()-jLabel4.getHeight();
    }//GEN-LAST:event_jLabel4MouseDragged

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        // TODO add your handling code here:
        jLabel5.setLocation(jLabel5.getLocation().x+evt.getX()-jLabel5.getWidth()/2, jLabel5.getLocation().y+evt.getY()-jLabel5.getHeight());
        lb5x=jLabel5.getLocation().x+evt.getX()-jLabel5.getWidth()/2;
        lb5y=jLabel5.getLocation().y+evt.getY()-jLabel5.getHeight();
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        // TODO add your handling code here:
        jLabel6.setLocation(jLabel6.getLocation().x+evt.getX()-jLabel6.getWidth()/2, jLabel6.getLocation().y+evt.getY()-jLabel7.getHeight());
        lb6x=jLabel6.getLocation().x+evt.getX()-jLabel6.getWidth()/2;
        lb6y=jLabel6.getLocation().y+evt.getY()-jLabel6.getHeight();
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        // TODO add your handling code here:
        jLabel7.setLocation(jLabel7.getLocation().x+evt.getX()-jLabel7.getWidth()/2, jLabel7.getLocation().y+evt.getY()-jLabel7.getHeight());
        lb7x=jLabel7.getLocation().x+evt.getX()-jLabel7.getWidth()/2;
        lb7y=jLabel7.getLocation().y+evt.getY()-jLabel7.getHeight();
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        // TODO add your handling code here:
        jLabel8.setLocation(jLabel8.getLocation().x+evt.getX()-jLabel8.getWidth()/2, jLabel8.getLocation().y+evt.getY()-jLabel8.getHeight());
        lb11x=jLabel18.getLocation().x+evt.getX()-jLabel18.getWidth()/2;
        lb11y=jLabel18.getLocation().y+evt.getY()-jLabel18.getHeight();
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        // TODO add your handling code here:
        jLabel9.setLocation(jLabel9.getLocation().x+evt.getX()-jLabel9.getWidth()/2, jLabel9.getLocation().y+evt.getY()-jLabel9.getHeight());
        lb9x=jLabel9.getLocation().x+evt.getX()-jLabel9.getWidth()/2;
        lb9y=jLabel9.getLocation().y+evt.getY()-jLabel9.getHeight();
    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        jLabel1.setLocation(jLabel1.getLocation().x+evt.getX()-jLabel1.getWidth()/2, jLabel1.getLocation().y+evt.getY()-jLabel1.getHeight());
        lb11x=jLabel11.getLocation().x+evt.getX()-jLabel11.getWidth()/2;
        lb11y=jLabel11.getLocation().y+evt.getY()-jLabel11.getHeight();
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged
        // TODO add your handling code here:
        jLabel11.setLocation(jLabel11.getLocation().x+evt.getX()-jLabel11.getWidth()/2, jLabel11.getLocation().y+evt.getY()-jLabel11.getHeight());
        lb11x=jLabel11.getLocation().x+evt.getX()-jLabel11.getWidth()/2;
        lb11y=jLabel11.getLocation().y+evt.getY()-jLabel11.getHeight();
    }//GEN-LAST:event_jLabel11MouseDragged

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
        // TODO add your handling code here:
        jLabel12.setLocation(jLabel12.getLocation().x+evt.getX()-jLabel12.getWidth()/2, jLabel12.getLocation().y+evt.getY()-jLabel12.getHeight());
        lb12x=jLabel12.getLocation().x+evt.getX()-jLabel12.getWidth()/2;
        lb12y=jLabel12.getLocation().y+evt.getY()-jLabel12.getHeight();
    }//GEN-LAST:event_jLabel12MouseDragged

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        // TODO add your handling code here:
        jLabel13.setLocation(jLabel13.getLocation().x+evt.getX()-jLabel13.getWidth()/2, jLabel13.getLocation().y+evt.getY()-jLabel13.getHeight());
        lb13x=jLabel13.getLocation().x+evt.getX()-jLabel13.getWidth()/2;
        lb13y=jLabel13.getLocation().y+evt.getY()-jLabel13.getHeight();
    }//GEN-LAST:event_jLabel13MouseDragged

    private void jLabel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseDragged
        // TODO add your handling code here:
        jLabel14.setLocation(jLabel14.getLocation().x+evt.getX()-jLabel14.getWidth()/2, jLabel14.getLocation().y+evt.getY()-jLabel14.getHeight());
        lb14x=jLabel11.getLocation().x+evt.getX()-jLabel14.getWidth()/2;
        lb14y=jLabel11.getLocation().y+evt.getY()-jLabel14.getHeight();
    }//GEN-LAST:event_jLabel14MouseDragged

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        // TODO add your handling code here:
        jLabel15.setLocation(jLabel15.getLocation().x+evt.getX()-jLabel15.getWidth()/2, jLabel15.getLocation().y+evt.getY()-jLabel15.getHeight());
        lb15x=jLabel15.getLocation().x+evt.getX()-jLabel15.getWidth()/2;
        lb15y=jLabel15.getLocation().y+evt.getY()-jLabel15.getHeight();
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel16MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseDragged
        // TODO add your handling code here:
        jLabel16.setLocation(jLabel16.getLocation().x+evt.getX()-jLabel16.getWidth()/2, jLabel16.getLocation().y+evt.getY()-jLabel16.getHeight());
        lb16x=jLabel16.getLocation().x+evt.getX()-jLabel16.getWidth()/2;
        lb16y=jLabel16.getLocation().y+evt.getY()-jLabel16.getHeight();
    }//GEN-LAST:event_jLabel16MouseDragged

    private void jLabel17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseDragged
        // TODO add your handling code here:
        jLabel17.setLocation(jLabel17.getLocation().x+evt.getX()-jLabel17.getWidth()/2, jLabel17.getLocation().y+evt.getY()-jLabel17.getHeight());
        lb17x=jLabel17.getLocation().x+evt.getX()-jLabel17.getWidth()/2;
        lb17y=jLabel17.getLocation().y+evt.getY()-jLabel17.getHeight();
    }//GEN-LAST:event_jLabel17MouseDragged

    private void jLabel18MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseDragged
        // TODO add your handling code here:
        jLabel18.setLocation(jLabel18.getLocation().x+evt.getX()-jLabel18.getWidth()/2, jLabel18.getLocation().y+evt.getY()-jLabel18.getHeight());
        lb18x=jLabel18.getLocation().x+evt.getX()-jLabel18.getWidth()/2;
        lb18y=jLabel18.getLocation().y+evt.getY()-jLabel18.getHeight();
    }//GEN-LAST:event_jLabel18MouseDragged

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
         // Aquí se pone en marcha el timer cada segundo.
      
        
         //.....
        jLabel2.setLocation(280,140);
        jLabel3.setLocation(280,200);
        jLabel4.setLocation(280,255);
        jLabel5.setLocation(280,315);
        jLabel6.setLocation(248,113);//2
        jLabel7.setLocation(250,168);
        jLabel8.setLocation(250,228);
        jLabel9.setLocation(250,285);
        //otro
        jLabel11.setLocation(425,113);
        jLabel12.setLocation(425,168);
        jLabel13.setLocation(425,230);
        jLabel14.setLocation(425,285);
        jLabel15.setLocation(455,140);//2
        jLabel16.setLocation(455,200);
        jLabel17.setLocation(455,255);
        jLabel18.setLocation(455,315);
        t.start();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        //rutina para guardar jugada...
        
        
            
           
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here: ver ck
        
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        //save
        String newline = System.lineSeparator();
        String cBotonesNegras =lb2x+" "+lb2y+newline+lb3x+" "+lb3y+newline+lb4x+" "+lb4y+newline+lb5x+" "+lb5y+newline+lb6x+" "+lb6y+newline+lb7x+" "+lb7y+newline+lb8x+" "+lb8y+newline+lb9x+" "+lb9y;
        String cAmarillas=lb11x+" "+lb11y+newline+lb12x+" "+lb12y+newline+lb13x+" "+lb13y+newline+lb14x+" "+lb14y+newline+lb15x+" "+lb15y+newline+lb16x+" "+lb16y+newline+lb17x+" "+lb17y+newline+lb18x+" "+lb18y;
        txtContenido.setText(etiquetaTiempo.getText()+newline+cBotonesNegras+newline+cAmarillas);
        t.stop();
        if (seleccionar.showDialog(null,"Guardar partida")==JFileChooser.APPROVE_OPTION) {
            archivo=seleccionar.getSelectedFile();//"perro";//=Area de datos
            if (archivo.getName().endsWith("txt")){
                String Documento=txtContenido.getText();  //txtarea-getText();
                String mensaje=GuardarArchivo(archivo, Documento);
                if(mensaje!=null){
                   
                    JOptionPane.showMessageDialog(null, mensaje);
                         
                }else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatiblr");
                  }
                } else { JOptionPane.showMessageDialog(null, "Archivo Guardado");
                  }
            }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //open
        if (seleccionar.showDialog(null, "Abrir partida")==JFileChooser.APPROVE_OPTION) {
            archivo=seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if (archivo.getName().endsWith("txt")){
                    String documento=AbrirArchivo(archivo);
                    txtContenido.setText(documento);
                    String [] lineas = documento.split("\n");
                    etiquetaTiempo.setText(lineas[0]);
                    String[] partes=lineas[1].split(" ");
                    //System.out.println(partes[0]+" y "+partes[1]);
                    jLabel2.setLocation(Integer.valueOf(partes[0]),Integer.valueOf(partes[1]));
                    //jLabel2.setLocation(301,111);
                    //System.out.println(lineas[0]);
                    //System.out.println(lineas[1]);
                    //jLabel2.setLocation(280,140);
                    //jLabel3.setLocation(280,200);
                    //jLabel4.setLocation(280,255);
                    //jLabel5.setLocation(280,315);
                    JOptionPane.showMessageDialog(null, txtContenido.getText());
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible");
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        //open
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem4MouseClicked

    /**
     * @param args the command line arguments
     */
    
   

    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTablero().setVisible(true);
                //ojo
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etiquetaTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbTablero;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
